version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_product
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: fact_order_items_enriched
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

  - name: fact_revenue_by_day
    columns:
      - name: order_date
        tests: [not_null, unique]
