version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: order_purchase_timestamp
        tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_order_items
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]

  - name: stg_payments
    columns:
      - name: order_id
        tests: [not_null]
